# Generated by Django 4.1 on 2022-09-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0011_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='products_in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
