# Generated by Django 4.1 on 2022-09-20 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0012_product_free_delivery_product_products_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2022, 9, 20, 14, 39, 34, 996945), verbose_name='дата создания'),
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_reviews',
            field=models.IntegerField(default=0, verbose_name='количество отзывов'),
        ),
    ]
