# Generated by Django 4.1 on 2022-09-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0014_alter_product_date_of_creation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
