# Generated by Django 4.1 on 2022-09-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0016_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review_product',
            field=models.ManyToManyField(related_name='product_review', to='app_product.product'),
        ),
    ]
