# Generated by Django 4.1 on 2022-09-28 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0017_alter_reviews_review_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-created'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
