# Generated by Django 4.1 on 2022-10-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0019_product_description_en_product_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
